--  Generate SQL 
--  Version:                   	V7R5M0 220415 
--  Generated on:              	11/02/22 20:25:04 
--  Relational Database:       	SEMILLAS 
--  Standards Option:          	Db2 for i 
CREATE TABLE JBUSTOS2.CLIENTES ( 
	CEDULA VARCHAR(15) CCSID 37 NOT NULL , 
	NOMBRE VARCHAR(40) CCSID 37 DEFAULT NULL , 
	FECNAC DATE DEFAULT NULL , 
	SALARIO NUMERIC(13, 2) DEFAULT NULL , 
	DIRECCION VARCHAR(100) CCSID 37 DEFAULT NULL , 
	USUCREO VARCHAR(10) CCSID 37 DEFAULT NULL , 
	FECCREO DATE DEFAULT NULL , 
	USUMOD VARCHAR(10) CCSID 37 DEFAULT NULL , 
	FECMOD DATE DEFAULT NULL , 
	CONSTRAINT JBUSTOS2.Q_MHERRERA1_CLIENTES_CEDULA_00001 PRIMARY KEY( CEDULA ) )   
	  
	RCDFMT CLIENTES   ; 
  
LABEL ON TABLE JBUSTOS2.CLIENTES 
	IS 'MAESTRO DE CLIENTES' ; 
  
LABEL ON COLUMN JBUSTOS2.CLIENTES 
( CEDULA TEXT IS 'CEDULA DEL CLIENTE' , 
	NOMBRE TEXT IS 'Nombre del cliente' , 
	FECNAC TEXT IS 'Fecha de nacimiento' , 
	SALARIO TEXT IS 'Salario mensual' , 
	DIRECCION TEXT IS 'Dirección del cliente' , 
	USUCREO TEXT IS 'Usuario que creo' , 
	FECCREO TEXT IS 'Fecha de creación' , 
	USUMOD TEXT IS 'Fecha de creación' , 
	FECMOD TEXT IS 'Fecha de última modificación' ) ; 
  
GRANT ALTER , DELETE , INDEX , INSERT , REFERENCES , SELECT , UPDATE   
ON JBUSTOS2.CLIENTES TO JBUSTOS WITH GRANT OPTION ; 
  
