--  Generate SQL 
--  Version:                   	V7R5M0 220415 
--  Generated on:              	11/02/22 20:39:18 
--  Relational Database:       	SEMILLAS 
--  Standards Option:          	Db2 for i 
CREATE TABLE JBUSTOS2.CUAPAGOS ( 
	NUMPRESTAMO FOR COLUMN NUMPR00001 NUMERIC(10, 0) NOT NULL , 
	NUMCUOTA NUMERIC(4, 0) NOT NULL , 
	FECHA DATE NOT NULL , 
	FECHAPAG DATE NOT NULL , 
	CUOTA NUMERIC(13, 2) NOT NULL , 
	CAPITAL NUMERIC(13, 2) NOT NULL , 
	INTERESES NUMERIC(13, 2) NOT NULL , 
	SALDOANT NUMERIC(13, 2) NOT NULL , 
	NUESALDO NUMERIC(13, 2) NOT NULL , 
	IDPAGO NUMERIC(10, 0) NOT NULL , 
	USUCREO VARCHAR(10) CCSID 37 NOT NULL , 
	FECCREO DATE NOT NULL , 
	USUMOD VARCHAR(10) CCSID 37 NOT NULL , 
	FECHAMOD DATE NOT NULL , 
	CONSTRAINT JBUSTOS2.Q_JBUSTOS2_CUAPAGOS_NUMPR00001_00001 PRIMARY KEY( NUMPRESTAMO , NUMCUOTA ) )   
	  
	RCDFMT CUAPAGOS   ; 
  
LABEL ON TABLE JBUSTOS2.CUAPAGOS 
	IS 'TABLA CUADRO DE PAGOS' ; 
  
LABEL ON COLUMN JBUSTOS2.CUAPAGOS 
( NUMPRESTAMO TEXT IS 'NUMERO DE PRESTAMO' , 
	NUMCUOTA TEXT IS 'NUMERO DE CUOTA' , 
	FECHA TEXT IS 'FECHA DE PAGO' , 
	FECHAPAG TEXT IS 'FECHA EN QUE SE PAGA' , 
	CUOTA TEXT IS 'CUOTA A PAGAR' , 
	CAPITAL TEXT IS 'CAPITAL APLICADO' , 
	INTERESES TEXT IS 'MONTO DE INTERESES' , 
	SALDOANT TEXT IS 'SALDO ANTERIOR' , 
	NUESALDO TEXT IS 'NUEVO SALDO' , 
	IDPAGO TEXT IS 'ID DEL PAGO' , 
	USUCREO TEXT IS 'USUARIO QUE CREO' , 
	FECCREO TEXT IS 'FECHA DE CREACION' , 
	USUMOD TEXT IS 'ULTIMO USUARIO QUE MODIFICO' , 
	FECHAMOD TEXT IS 'FECHA DE ULTIMA MODIFICACION' ) ; 
  
GRANT ALTER , DELETE , INDEX , INSERT , REFERENCES , SELECT , UPDATE   
ON JBUSTOS2.CUAPAGOS TO JBUSTOS WITH GRANT OPTION ; 
  
