--  Generate SQL 
--  Version:                   	V7R5M0 220415 
--  Generated on:              	11/02/22 20:37:08 
--  Relational Database:       	SEMILLAS 
--  Standards Option:          	Db2 for i 
CREATE TABLE JBUSTOS2.PAGOS ( 
	IDPAGO NUMERIC(10, 0) NOT NULL , 
	NUMPRESTAMO FOR COLUMN NUMPR00001 NUMERIC(10, 0) NOT NULL , 
	FECHA DATE NOT NULL , 
	MONTOPAG NUMERIC(13, 2) NOT NULL , 
	CAPITAL NUMERIC(13, 2) NOT NULL , 
	INTERESES NUMERIC(13, 2) NOT NULL , 
	SALDOANT NUMERIC(13, 2) NOT NULL , 
	NUESALDO NUMERIC(13, 2) NOT NULL , 
	USUCREO VARCHAR(10) CCSID 37 DEFAULT NULL , 
	FECCREO DATE DEFAULT NULL , 
	USUMOD VARCHAR(10) CCSID 37 DEFAULT NULL , 
	FECMOD DATE DEFAULT NULL )   
	  
	RCDFMT PAGOS      ; 
  
ALTER TABLE JBUSTOS2.PAGOS 
	ADD CONSTRAINT JBUSTOS2.Q_JBUSTOS2_PAGOS_IDPAGO_00001 
	UNIQUE( IDPAGO ) ; 
  
LABEL ON TABLE JBUSTOS2.PAGOS 
	IS 'Pagos a Prestamos' ; 
  
LABEL ON COLUMN JBUSTOS2.PAGOS 
( IDPAGO TEXT IS 'Número de pago' , 
	NUMPRESTAMO TEXT IS 'Número de préstamo' , 
	FECHA TEXT IS 'Fecha del pago' , 
	MONTOPAG TEXT IS 'Monto pagado' , 
	CAPITAL TEXT IS 'Capital aplicado' , 
	INTERESES TEXT IS 'Monto de intereses' , 
	SALDOANT TEXT IS 'Saldo Anterior' , 
	NUESALDO TEXT IS 'Nuevo Saldo' , 
	USUCREO TEXT IS 'Usuario que creo' , 
	FECCREO TEXT IS 'Fecha de creación' , 
	USUMOD TEXT IS 'Ultimo usuario que modifico' , 
	FECMOD TEXT IS 'Fecha de última modificación' ) ; 
  
GRANT ALTER , DELETE , INDEX , INSERT , REFERENCES , SELECT , UPDATE   
ON JBUSTOS2.PAGOS TO JBUSTOS WITH GRANT OPTION ; 
  
